Filter Panel: UI button margin and icon.
livgust/macovidvaccines.com pull request #121
Opened 2021-03-06 13:51 UTC by harcod

Fixed margin for "Update List" button on mobile.
Changed icon on "Filter Locations" button.

![image](https://user-images.githubusercontent.com/546007/110209088-8c3d9500-7e58-11eb-95e0-e06699008709.png)

**AFTER:**
![image](https://user-images.githubusercontent.com/546007/110209172-f5250d00-7e58-11eb-9372-852c1567a0e5.png)

**BEFORE:**
![image](https://user-images.githubusercontent.com/546007/110209155-e4749700-7e58-11eb-912b-302777d8d8f4.png)

2021-03-06 22:17 UTC, livgust requested changes
One small comment barely related to the PR.
Confirmed that the new icon matches the one on our spec from UX. Thank you!

2021-03-06 22:17 UTC, livgust commented on src/App.js
> -//import { Alert, AlertTitle } from "@material-ui/lab";
Could you put this back in, please? It's so it's easy to uncomment when we want to put an alert back in.

2021-03-07 00:45 UTC, livgust approved these changes

2021-03-07 03:26 UTC, iann approved these changes

2021-03-07 03:26 UTC, iann commented on src/App.js
> +    mobileButton: { width: "50%", marginLeft: theme.spacing(3) },
Thank you! That margin was bugging me on mobile.

2021-03-07 03:28 UTC, merged