Basic React Router installation
livgust/macovidvaccines.com pull request #184
Opened 2021-04-26 18:37 UTC by harcod

There is one route "/about" that shows a prototype for an About Us page.  There is no direct navigation to this page in this PR.

"/" shows the current site <App />
"/about" shows the prototype for an About Us page. <About />
every other route redirects to "/" (otherwise we would get a 404 error).

2021-04-26 18:50 UTC, harcod commented
I fixed the "color contrast" Lighthouse error, but now the rel-preconnect fails again.

> uses-rel-preconnect` failure for `maxLength` assertion (Preconnect to required origins: https://web.dev/uses-rel-preconnect/ )

2021-04-26 22:07 UTC, livgust requested changes
Thanks for this, it looks good! 2 tiny nits.

2021-04-26 22:07 UTC, livgust commented on src/About.js
> +                    send an email send Olivia email
I like "send an email"

2021-04-26 22:07 UTC, livgust commented on src/About.js
> +            {/*            https://www.cnn.com/videos/health/2021/02/08/software-developer-builds-simple-massachusetts-covid-19-vaccine-website-olivia-adams-intv-newday-vpx.cnn*/}
Mind taking this out?

2021-04-27 13:27 UTC, livgust approved these changes

2021-04-27 13:27 UTC, merged